framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    session:
        enabled: true

when@dev:
    framework:
        ide: null

when@test:
    framework:
        test: true
        secret: 'test_secret' # Default value for APP_SECRET in test environment
        session:
            storage_factory_id: session.storage.factory.mock_file
